### PR TITLE
Fix Test Bugs

### LINKED ISSUE #252: Problem: regression tests do not pass locally on main
on the latest commit for main (05f5221), the regression tests do not pass on my local machine. the consistently failing test is `test_best_canonical_tip` which is failing with the error `Error: invalid type: string "No summary available yet", expected struct SummaryShort at line 1 column 26`

### PR DESCRIPTION
**Pull request by jenr24G**
This pull request fixes the inconsistencies with running the regression test suite locally, as well as some QoL changes regarding removing dangling socket files, etc.

Closes #252, #251

### CODE REVIEW

File: src/server.rs [hunk 1]
```diff
@@ -295,26 +232,32 @@ pub async fn initialize(
...
             root_hash.clone(),
-            ledger.ledger,
+            ledger.ledger.clone(),
             store,
             MAINNET_TRANSITION_FRONTIER_K,
             prune_interval,
             canonical_update_threshold,
         )?;
 
+        info!("Getting best tip");
```
Comment (trevorbernard) [inline src/server.rs:242]: These should be debug. Non-blocking

File: src/server.rs [hunk 2]
```diff
@@ -350,11 +289,11 @@ pub async fn run(
     block_watch_dir: impl AsRef<Path>,
     mut state: IndexerState,
     phase_sender: Arc<watch::Sender<MinaIndexerRunPhase>>,
-    mut query_receiver: mpsc::Receiver<(
+    mut query_receiver: mpsc::UnboundedReceiver<(
```
Comment (trevorbernard) [inline src/server.rs:292]: Using an unbounded array for IPC is dubious. I would prefer to see it bounded but something more reasonable than `50` like `1024`. Non-blocking

**Review by trevorbernard — APPROVED** [review]
